name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Check for requirements.txt
      - name: Check for requirements.txt
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo "requirements.txt not found! Exiting..."
            exit 1
          fi

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Check for test files
      - name: Check for test files
        run: |
          if ! ls tests/example_test.py 2>/dev/null && ! ls tests/example_test.py 2>/dev/null; then
            echo "No test files found! Exiting..."
            exit 1
          fi

      # Run unittests
      - name: Run unittest
        run: python -m unittest discover -s tests -p 'tests/example_test.py'

      # Run pytest
      - name: Run pytest
        run: pytest --junitxml=pytest-report.xml
