name: Deploy Swagger API to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allow manual workflow triggers

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # EC2 private key stored as a GitHub Secret

    - name: Deploy Swagger API on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Update system packages
          sudo yum update -y
          
          # Install git and clone the repository
          sudo yum install git -y
          git clone https://github.com/Ashwini-Kanagaraj/swagger_server02.git
          cd swagger_server02
          
          # Install Python and pip
          sudo yum install python3 -y
          sudo yum install python3-pip -y
          
          # Install dependencies
          sudo pip3 install flasgger
          pip3 install -r requirements.txt
          sudo pip3 install Flask Flask-RESTful flask-swagger-ui
          
          # Run the Flask app
          nohup python3 app.py > app.log 2>&1 &
        EOF

    - name: Output Swagger URL
      run: |
        IP=$(echo "${{ secrets.EC2_PUBLIC_IP }}" | sed 's/\./-/g')
        echo "Swagger API deployed successfully!"
        echo "Access the Swagger UI at http://${IP}:5001/apidocs"








