name: Deploy API Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-swagger-ui

    - name: Set up SSH Key
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh                         # Ensure the .ssh directory exists
        echo "${SSH_KEY}" > ~/.ssh/id_rsa       # Save the private key
        chmod 600 ~/.ssh/id_rsa                 # Set proper permissions for the private key
        ssh-keyscan -H 54.161.43.43 >> ~/.ssh/known_hosts || true  # Add EC2 host to known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.161.43.43 << 'EOF'
          cd /path/to/your/app
          git pull origin main
          python3 -m pip install --upgrade pip
          pip install flask flask-swagger-ui
          pkill -f app.py || true
          nohup python3 app.py &
        EOF
