name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup SSH key for EC2 access
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Install Python
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Navigate to the app directory or clone the repo
          if [ ! -d "app" ]; then
            git clone https://github.com/yourusername/your-repo.git app
          else
            cd app && git pull
          fi

          # Create a virtual environment and install dependencies
          cd app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Run Gunicorn
          pkill gunicorn || true
          nohup gunicorn --bind 0.0.0.0:5000 app:app &
        EOF
